## This rule redirects to an external API
[[redirects]]
  from = "/api/*"
  to = "https://realm.mongodb.com/api/client/v2.0/app/data-jgazm/graphql:splat"
  status = 200
  headers = {X-From = "Netlify"}


## https://vim9ip3utf.execute-api.us-west-1.amazonaws.com/latest/iiif/2/test%2Fuic.png/full/300,/0/default.png
[[redirects]]
  from = "/iiif/*"
  to = "https://vim9ip3utf.execute-api.us-west-1.amazonaws.com/latest/iiif/2/:splat"
  status = 200

## https://bcw-images.s3.us-west-1.amazonaws.com/brachio/visits/v1_0/ca_utoronto_library_3185385819_20050908182525/w320.png
[[redirects]]
  from = "/s3/"
  to = "https://bcw-images.s3.us-west-1.amazonaws.com/brachio/:splat"
  status = 200

## catch all rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200